# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('int_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Is hidden'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Is hidden'),
        ),
    ]
