# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('int_shop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='Author'),
        ),
    ]
