# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('int_shop', '0003_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(default=None, null=True, related_name='carts', to='int_shop.CartItem', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='int_shop.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
