# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('int_shop', '0003_auto_20160608_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='carts', to='int_shop.CartItem', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
    ]
