# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('int_shop', '0004_auto_20160614_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Number of pages')),
                ('cover', models.CharField(blank=True, max_length=50, verbose_name='Cover')),
                ('publisher', models.CharField(blank=True, max_length=50, verbose_name='Publisher')),
                ('year', models.DateField(blank=True, null=True, verbose_name='Publish date')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='int_shop.ProductFeatures', verbose_name='Features'),
        ),
    ]
