# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('int_shop', '0005_auto_20160614_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cover'),
        ),
        migrations.AddField(
            model_name='product',
            name='pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of pages'),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(blank=True, max_length=50, verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.DateField(blank=True, null=True, verbose_name='Publish date'),
        ),
        migrations.DeleteModel(
            name='ProductFeatures',
        ),
    ]
