# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('int_shop', '0007_auto_20160614_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pages',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Number of pages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Publish date'),
        ),
    ]
