# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('int_shop', '0009_auto_20160614_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='int_shop.Category', verbose_name='Parent category'),
        ),
    ]
