# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('int_shop', '0010_auto_20160614_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
