# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 12:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('int_shop', '0012_auto_20160615_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('url', models.URLField(verbose_name='URL')),
                ('is_active', models.BooleanField(verbose_name='Is active')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=255, verbose_name='Slug')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('template', models.CharField(max_length=255, verbose_name='Template')),
                ('email_template', models.TextField(verbose_name='Email Template')),
                ('sender', models.EmailField(max_length=254, verbose_name='Sender')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default=None, null=True, upload_to=b'', verbose_name='Image')),
                ('birth_date', models.DateField(default=None, verbose_name='Date of Birth')),
                ('city', models.CharField(default=None, max_length=255, verbose_name='City')),
                ('country', models.CharField(default=None, max_length=255, verbose_name='Country')),
                ('address', models.TextField(default=None, verbose_name='Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.IntegerField(default=0, verbose_name='In stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.IntegerField(default=0, verbose_name='Sold'),
        ),
        migrations.AddField(
            model_name='product',
            name='votes_count',
            field=models.IntegerField(default=0, verbose_name='Voted'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='int_shop.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
