# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('int_shop', '0013_auto_20160617_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(related_name='wish_lists', to='int_shop.Product', verbose_name='Product'),
        ),
    ]
