# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('int_shop', '0015_auto_20160617_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
