# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('int_shop', '0017_auto_20160617_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Ordering'),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='int_shop.Product', verbose_name='Product'),
        ),
    ]
