# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('int_shop', '0019_productproperty_productpropertyvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproperty',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
