# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('int_shop', '0020_productproperty_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='int_shop.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='title',
            field=models.CharField(default='', max_length=128, verbose_name='Property Title'),
        ),
        migrations.AlterField(
            model_name='productpropertyvalue',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='int_shop.ProductProperty', verbose_name='Property Title'),
        ),
        migrations.AlterField(
            model_name='productpropertyvalue',
            name='title',
            field=models.CharField(default='', max_length=128, verbose_name='Property Value'),
        ),
    ]
